language: node_js
node_js:
- stable
- '6'
- '4'
deploy:
  api_key:
    secure: CSaMqkhkQ4uHlZxxYi38+Q2bhbG4DShl4wGwuGJ2+JbS7tX7Weqvs9HzD6akDDRwWBW7X66oswmmKhIEl9rfYbSRdupqlX2cIR+jHxidn9s1qFVPdq2IiSODgfzaRvdK3Zw5FOMGwvgnBGq1JaPE+b2KA9QvRIQqhtU0A7LhfJYaNWs9mha74YcNSLJMCeRzL86T8Xtad/QJQv2LqxqXVA8orM+f2u27DFywPLvI8oUZE34eCgNdPDEzHMzWiLG+C7fEGel2gGRQsUNUQDO9NOupqi87fdnjxdT4pgE/kE9+yTUpZYfOCABgoJotOE/q6ehIg3tqS37JBiBbh+dBw92gjskc4gbQWwx9X2DFAosNGRV7Mp2FwkpjzZxdPEwfab3eOfo52SVtqpisfRSBUfD2bJG/BwN33Xksq09cBOHlIsyt+rydoUGrRQs1gl/C2Gll6y1JvUF7cSUKvE8Whddh86zjBIKTR38CCJY8yYF6+n2j0Zvmnw8P3aa/9+flCsZ5eFB3UL4TgvY8E9TtOZNTZCR9ZN/yAIVV4SSTORyw85zcI3qpCp9/7K4CFqB0tjvzXlclVlwn1RYajfkYVKGKj6OETkubuD9iQjpsvMf3pG0X2ad+aCWNdPafmCUjSaFUSC5mmIbQJ9vc1GiWxnBduy5HSt1jRde/d6ShjYI=
